export enum Events {
    "Hello" = "Hello",
    "Ready" = "Ready",
    "Resumed" = "Resumed",
    "InvalidSession" = "Invalid Session",
    "ChannelCreate" = "Channel Create",
    "ChannelUpdate" = "Channel Update",
    "ChannelDelete" = "Channel Delete",
    "GuildCreate" = "Guild Create",
    "GuildUpdate" = "Guild Update",
    "GuildDelete" = "Guild Delete",
    "GuildBanAdd" = "Guild Ban Add",
    "GuildBanRemove" = "Guild Ban Remove",
    "GuildMemberAdd" = "Guild Member Add",
    "GuildMemberRemove" = "Guild Member Remove",
    "GuildMemberUpdate" = "Guild Member Update",
    "GuildRoleCreate" = "Guild Role Create",
    "GuildRoleDelete" = "Guild Role Delete",
    "GuildRoleUpdate" = "Guild Role Update",
    "UserUpdate" = "User Update",
    "PresenceUpdate" = "Presence Update",
    "TypingStart" = "Typing Start",
    "VoiceStateUpdate" = "Voice State Update",
    "VoiceServerUpdate" = "Voice Server Update"
}